version: '3.7'

services:

    letsencrypt:
        image: linuxserver/letsencrypt
        environment:
            - TZ=America/New_York
            - URL=${DCC_INSTANCE}
            - VALIDATION=http
            - EMAIL=dabrown@syr.edu
            - DHLEVEL=2048
            - ONLY_SUBDOMAINS=false
            - STAGING=false
        volumes:
            - ${STORAGE_PATH}/letsencrypt/config:/config
        networks:
            - dcc-net
        ports:
            - "80:80"
        deploy:
          replicas: 0

    docdb-database:
        image: mariadb:10.4.8
        volumes:
            - ${STORAGE_PATH}/var/lib/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
        secrets:
            - mariadb_root_password
        networks:
            - dcc-net
        deploy:
            replicas: 1

    rest-api:
        image: cosmicexplorer/rest-dcc:1.2.1
        init: true
        secrets:
            - mysql_docdbrw_passwd
        networks:
            - dcc-net
        deploy:
            replicas: 1

    oauth-database:
        image: postgres:9.6
        volumes:
            - ${STORAGE_PATH}/var/lib/postgresql/data:/var/lib/postgresql/data
        networks:
            - dcc-net
        deploy:
            replicas: 1

    oauth-server:
        image: oryd/hydra:v1.0.8
        environment:
            - SECRETS_SYSTEM=${SECRETS_SYSTEM}
            - DSN=postgres://hydra:${HYDRA_PASSWD}@oauth-database:5432/hydra?sslmode=disable
            - URLS_SELF_ISSUER=https://${DCC_INSTANCE}/oauth/
            - URLS_CONSENT=https://${DCC_INSTANCE}/consent
            - URLS_LOGIN=https://${DCC_INSTANCE}/login
            - LOG_LEVEL=debug
            - HTTPS_ALLOW_TERMINATION_FROM=172.30.101.0/24
        networks:
            - dcc-net
        command: "serve all"
        deploy:
            replicas: 1

    oauth-consent:
        image: cosmicexplorer/hydra-login-consent-node:1.0.9
        environment:
            - HYDRA_ADMIN_URL=http://oauth-server:4445
            - MOCK_TLS_TERMINATION=y
        secrets:
            - shib_header_secret
        networks:
            - dcc-net
        deploy:
            replicas: 1

    dcc:
        image: cosmicexplorer/dcc:3.3.0
        volumes:
            - ${STORAGE_PATH}/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
            - ${STORAGE_PATH}/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml
            - ${STORAGE_PATH}/etc/shibboleth/inc-md-cert.pem:/etc/shibboleth/inc-md-cert.pem
            - ${STORAGE_PATH}/usr1/www/html/DocDB:/usr1/www/html/DocDB
            - ${STORAGE_PATH}/usr1/www/html/public:/usr1/www/html/public
            - ${STORAGE_PATH}/var/lib/mysql:/var/lib/mysql
            - ${STORAGE_PATH}/usr2/GLIMPSE:/usr2/GLIMPSE
            - ${STORAGE_PATH}/letsencrypt/config/etc/letsencrypt:/etc/letsencrypt
        secrets:
            - shibboleth_sp_encrypt_cert
            - shibboleth_sp_encrypt_privkey
            - mysql_root_passwd
            - mysql_docdbrw_passwd
            - mysql_docdbro_passwd
            - shib_header_secret
            - rest_authorized_eppn
        networks:
            - dcc-net
        ports:
            - "443:443"
        hostname: ${DCC_INSTANCE}
        dns:
            - 208.67.222.222
            - 208.67.220.220
        environment:
            - DCC_HOSTNAME=${DCC_HOSTNAME}
        deploy:
            replicas: 0            

networks:
    dcc-net:
        attachable: true
        ipam:
            driver: default
            config:
                - subnet: 172.30.101.0/24

secrets:
    mariadb_root_password:
        external: true
    shibboleth_sp_encrypt_cert:
        external: true
    shibboleth_sp_encrypt_privkey:
        external: true
    mysql_root_passwd:
        external: true
    mysql_docdbrw_passwd:
        external: true
    mysql_docdbro_passwd:
        external: true
    shib_header_secret:
        external: true
    rest_authorized_eppn:
        external: true
