version: '3.1'
services:
  dcc-bootstrap:
    image: cosmicexplorer/dcc-bootstrap:3.3.0
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ${STORAGE_PATH}/etc/shibboleth/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      - ${STORAGE_PATH}/etc/shibboleth/attribute-map.xml:/etc/shibboleth/attribute-map.xml
      - ${STORAGE_PATH}/etc/shibboleth/inc-md-cert.pem:/etc/shibboleth/inc-md-cert.pem
      - ${STORAGE_PATH}/usr1/www/html/DocDB:/usr1/www/html/DocDB
      - ${STORAGE_PATH}/usr1/www/html/public:/usr1/www/html/public
      - ${STORAGE_PATH}/var/lib/mysql:/var/lib/mysql
      - ${STORAGE_PATH}/usr2/GLIMPSE:/usr2/GLIMPSE
    ports:
      - "128.230.146.13:443:443"
    secrets:
      - shibboleth_sp_encrypt_cert
      - shibboleth_sp_encrypt_privkey
      - mysql_root_passwd
      - mysql_docdbrw_passwd
      - mysql_docdbro_passwd
      - mysql_hydra_passwd
    hostname: ${DCC_INSTANCE}
    domainname: ${DCC_DOMAINNAME}
    dns:
      - 208.67.222.222
      - 208.67.220.220
    environment:
      - DCC_HOSTNAME=${DCC_HOSTNAME}
      - DCC_DOMAINNAME=${DCC_DOMAINNAME}

secrets:
    shibboleth_sp_encrypt_cert:
         file: ${CERT_DIR}/sp-encrypt-cert.pem
    shibboleth_sp_encrypt_privkey:
         file: ${CERT_DIR}/sp-encrypt-key.pem
    mysql_root_passwd:
         file: ${CERT_DIR}/mysql_root_passwd.txt
    mysql_docdbrw_passwd:
         file: ${CERT_DIR}/mysql_docdbrw_passwd.txt
    mysql_docdbro_passwd:
         file: ${CERT_DIR}/mysql_docdbro_passwd.txt
    mysql_hydra_passwd:
         file: ${CERT_DIR}/mysql_hydra_passwd.txt
